config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    mount API::Root, at: "/"
    mount GrapeSwaggerRails::Engine, at: "/api-docs"
    namespace :admin do
      root "static_pages#index"
      get "login", to: "sessions#new"
      post "login", to: "sessions#create"
      get "logout", to: "sessions#destroy"
      resources :orders, except: %i(create destroy)
    end
    root "static_pages#index"
    get "/home", to: "static_pages#index"

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    get "/logout", to: "sessions#destroy"

    resources :products, only: %i(index show)
    resources :carts, except: %i(new show edit)
    resources :orders, only: %i(new create)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index; end

  def create
    @result = cart_handle_add
    respond_to do |format|
      format.js {}
    end
  end

  def update
    @result = cart_handle_remove
    respond_to do |format|
      format.js {}
    end
  end

  def destroy
    remove_item
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  # init cart only once
  def init_cart
    session[:cart] ||= {}
  end

  # wipe out all data in cart when logged out
  def empty_cart
    session[:cart] = {}
  end

  # number of available items in cart
  def cart_count
    return 0 if session[:cart].blank?

    cnt = 0
    session[:cart].each do |pair|
      cnt += Product.exists?(id: pair[0]) ? 1 : 0
    end

    cnt
  end

  # sum of all items
  def subtotal
    subtotal = 0
    if session[:cart].present?
      session[:cart].each do |pair|
        curr_price = item_attr :price, pair[0]
        subtotal += curr_price.any? ? curr_price[0] * pair[1] : 0
      end
    end

    subtotal.round(2)
  end

  # retrived items list exists in cart
  def cart_contents
    products_contents = {}
    session[:cart].each do |pair|
      product = basic_product_info pair[0]
      if product && product[:inventory].positive?
        session[:cart][pair[0]] = available_qty pair[1], product[:inventory]
        products_contents[pair] = product
      else
        session[:cart].delete(pair[0])
      end
    end

    products_contents
  end

  # increase item quantity from cart by 1
  def cart_handle_add
    return false unless item_exists

    possible_qty = session[:cart][params[:id]] || 0
    possible_qty += 1
    return :exceeded if qty_exceeds_range params[:id], possible_qty

    session[:cart][params[:id]] = possible_qty
    :added
  end

  # subtract item quantity from cart by 1
  def cart_handle_remove
    return false unless session[:cart][params[:id]]

    return :pending_remove if session[:cart][params[:id]] == 1

    session[:cart][params[:id]] -= 1
    :removed
  end

  # remove item from cart
  def remove_item
    session[:cart].delete(params[:id]) if session[:cart][params[:id]]
    :removed
  end

  def cart_is_empty?
    cart_count.zero?
  end

  private
  def item_exists
    Product.exists?(params[:id])
  end

  def item_attr attr, id
    Product.pluck_attr id, attr
  end

  def basic_product_info id
    Product.basic_product_info id
  end

  # current_qty cannot be larger than inventory
  def available_qty qty, inventory
    qty > inventory ? inventory : qty
  end

  # check if current_qty is larger than inventory
  def qty_exceeds_range id, qty
    inventory = item_attr :inventory, id
    return true unless inventory

    qty > inventory[0]
  end
end

app/views/carts/create.js.erb
<% msg = t("cart.modal.#{@result}") %>
$(".pending__popup").html("<%= j (render partial: "shared/modal", locals: {status: @result, msg: msg}) %>")
$("#exampleModalCenter").modal("show")
$(".cart__items").html("<%= j (render partial: "layouts/cart/cart_items") %>")
$("#cart__subtotal").html("<%= j (translate_price subtotal) %>")
$("#shopping__bag__count").html("<%= j (cart_count) %>")
$("#shopping__bag__total").html("<%= j (translate_price subtotal) %>")

app/views/carts/destroy.js.erb
$("#exampleModalCenter").modal("hide")
$(".cart__items").html("<%= j (render partial: "layouts/cart/cart_items") %>")
$("#cart__subtotal").html("<%= j (translate_price subtotal) %>")
$("#shopping__bag__count").html("<%= j (cart_count) %>")
$("#shopping__bag__total").html("<%= j (translate_price subtotal) %>")

app/views/carts/index.html.erb
<% provide :title, t("cart.page_title") %>

<!-- Shoping Cart Section Begin -->
<section class="shoping-cart spad">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="shoping__cart__table">
					<table>
						<thead>
							<tr>
								<th class="shoping__product"><%= t "cart.products" %></th>
								<th><%= t "cart.price" %></th>
								<th><%= t "cart.inventory" %></th>
								<th><%= t "cart.qty" %></th>
								<th><%= t "cart.total" %></th>
								<th></th>
							</tr>
						</thead>
						<tbody class="cart__items">
							<%= render "layouts/cart/cart_items" %>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="shoping__cart__btns">
					<%= link_to t("cart.btn.continue_shopping"), products_path, class: "primary-btn cart-btn" %>
					<%= link_to carts_path, class: "primary-btn cart-btn cart-btn-right" do %>
						<span class="icon_loading"> </span><%= t "cart.btn.update_cart" %>
					<% end %>
				</div>
			</div>
			<div class="col-lg-12">
				<div class="shoping__checkout">
					<h5><%= t "cart.cart_total" %></h5>
					<ul>
						<li>
							<%= t "cart.total" %>
							<span id="cart__subtotal"><%= translate_price subtotal %></span>
						</li>
					</ul>
					<%= link_to t("cart.btn.checkout"), new_order_path, class: "primary-btn" %>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- Shoping Cart Section End -->

app/views/carts/update.js.erb
<% msg = t("cart.modal.#{@result}") %>
$(".pending__popup").html("<%= j (render partial: "shared/modal", locals: {status: @result, msg: msg}) %>")
$("#exampleModalCenter").modal("show")
$(".cart__items").html("<%= j (render partial: "layouts/cart/cart_items") %>")
$("#cart__subtotal").html("<%= j (translate_price subtotal) %>")
$("#shopping__bag__count").html("<%= j (cart_count) %>")
$("#shopping__bag__total").html("<%= j (translate_price subtotal) %>")