config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    mount API::Root, at: "/"
    mount GrapeSwaggerRails::Engine, at: "/api-docs"
    namespace :admin do
      root "static_pages#index"
      get "login", to: "sessions#new"
      post "login", to: "sessions#create"
      get "logout", to: "sessions#destroy"
      resources :orders, except: %i(create destroy)
    end
    root "static_pages#index"
    get "/home", to: "static_pages#index"

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    get "/logout", to: "sessions#destroy"

    resources :products, only: %i(index show)
    resources :carts, except: %i(new show edit)
    resources :orders, only: %i(new create)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index; end

  def create
    @result = cart_handle_add
    respond_to do |format|
      format.js {}
    end
  end

  def update
    @result = cart_handle_remove
    respond_to do |format|
      format.js {}
    end
  end

  def destroy
    remove_item
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  # init cart only once
  def init_cart
    session[:cart] ||= {}
  end

  # wipe out all data in cart when logged out
  def empty_cart
    session[:cart] = {}
  end

  # number of available items in cart
  def cart_count
    return 0 if session[:cart].blank?

    cnt = 0
    session[:cart].each do |pair|
      cnt += Product.exists?(id: pair[0]) ? 1 : 0
    end

    cnt
  end

  # sum of all items
  def subtotal
    subtotal = 0
    if session[:cart].present?
      session[:cart].each do |pair|
        curr_price = item_attr :price, pair[0]
        subtotal += curr_price.any? ? curr_price[0] * pair[1] : 0
      end
    end

    subtotal.round(2)
  end

  # retrived items list exists in cart
  def cart_contents
    products_contents = {}
    session[:cart].each do |pair|
      product = basic_product_info pair[0]
      if product && product[:inventory].positive?
        session[:cart][pair[0]] = available_qty pair[1], product[:inventory]
        products_contents[pair] = product
      else
        session[:cart].delete(pair[0])
      end
    end

    products_contents
  end

  # increase item quantity from cart by 1
  def cart_handle_add
    return false unless item_exists

    possible_qty = session[:cart][params[:id]] || 0
    possible_qty += 1
    return :exceeded if qty_exceeds_range params[:id], possible_qty

    session[:cart][params[:id]] = possible_qty
    :added
  end

  # subtract item quantity from cart by 1
  def cart_handle_remove
    return false unless session[:cart][params[:id]]

    return :pending_remove if session[:cart][params[:id]] == 1

    session[:cart][params[:id]] -= 1
    :removed
  end

  # remove item from cart
  def remove_item
    session[:cart].delete(params[:id]) if session[:cart][params[:id]]
    :removed
  end

  def cart_is_empty?
    cart_count.zero?
  end

  private
  def item_exists
    Product.exists?(params[:id])
  end

  def item_attr attr, id
    Product.pluck_attr id, attr
  end

  def basic_product_info id
    Product.basic_product_info id
  end

  # current_qty cannot be larger than inventory
  def available_qty qty, inventory
    qty > inventory ? inventory : qty
  end

  # check if current_qty is larger than inventory
  def qty_exceeds_range id, qty
    inventory = item_attr :inventory, id
    return true unless inventory

    qty > inventory[0]
  end
end

app/views/layouts/cart/_cart_items.html.erb
<% if cart_contents.present? %>
  <% cart_contents.each do |item| %>
    <tr>
      <td class="shoping__cart__item">
        <img src="/img/cart/cart-1.jpg" alt="">
        <h5><%= item[1][:name] %></h5>
      </td>
      <td class="shoping__cart__price">
        <%= translate_price item[1][:price] %>
      </td>
      <td class="shoping__cart__price">
        <%= item[1][:inventory] %>
      </td>
      <td class="shoping__cart__quantity">
        <div class="quantity">
          <div class="pro-qty">
            <span class="dec qtybtn">
              <%= link_to "-", cart_path(id: item[1][:id]), method: :patch, remote: true %>
            </span>
            <input type="text" readonly="readonly" value=<%= item[0][1] %>>
            <span class="inc qtybtn">
              <%= link_to "+", carts_path(id: item[1][:id]), method: :post, remote: true %>
            </span>
          </div>
        </div>
      </td>
      <td class="shoping__cart__total">
        <%= translate_price item[0][1] * item[1][:price] %>
      </td>
    </tr>
  <% end %>
<% end %>

app/views/layouts/cart/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">
          <%= t "cart.modal.header" %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% if status == :exceeded %>
          <%= t "cart.modal.exceeded" %>
        <% else %>
          <%= t "cart.modal.pending_remove" %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          <%= t "cart.modal.btn_close" %>
        </button>
        <% if status == :pending_remove %>
          <%= button_to t("cart.modal.btn_confirm"),
                        cart_path(id: params[:id]),
                        method: :delete,
                        remote: true,
                        type: "button",
                        class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>