config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    mount API::Root, at: "/"
    mount GrapeSwaggerRails::Engine, at: "/api-docs"
    namespace :admin do
      root "static_pages#index"
      get "login", to: "sessions#new"
      post "login", to: "sessions#create"
      get "logout", to: "sessions#destroy"
      resources :orders, except: %i(create destroy)
    end
    root "static_pages#index"
    get "/home", to: "static_pages#index"

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    get "/logout", to: "sessions#destroy"

    resources :products, only: %i(index show)
    resources :carts, except: %i(new show edit)
    resources :orders, only: %i(new create)
  end
end

app/views/admin/layouts/_flash.html.erb
<div>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <div class="container text-center">
        <%= message.html_safe %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/layouts/_sidebar.html.erb
<!-- Sidebar -->
<ul class="navbar-nav sidebar sidebar-light accordion" id="accordionSidebar">
  <%= link_to admin_root_path, class: "sidebar-brand d-flex align-items-center justify-content-center" do %>
    <div class="sidebar-brand-icon">
      <img src="/img/logo/logo2.png">
    </div>
    <div class="sidebar-brand-text mx-3">RuangAdmin</div>
  <% end %>
  <hr class="sidebar-divider my-0">
  <li class="nav-item active">
    <%= link_to admin_root_path, class: "nav-link" do %>
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span><%= t ".dashboard" %></span>
    <% end %>
  </li>
  <hr class="sidebar-divider">
  <div class="sidebar-heading">
    <%= t ".pages" %>
  </div>
  <li class="nav-item">
    <%= link_to admin_orders_path, class: "nav-link" do %>
      <i class="fab fa-fw fa-wpforms"></i>
      <span><%= t ".orders" %></span>
    <% end %>
  </li>
  <hr class="sidebar-divider">
  <li class="nav-item">
    <%= link_to admin_logout_path, class: "nav-link" do %>
      <i class="fas fa-sign-out-alt"></i>
      <span><%= t ".logout" %></span>
    <% end %>
  </li>
  <hr class="sidebar-divider">
  <div class="version" id="version-ruangadmin"></div>
</ul>

app/views/admin/layouts/_topbar.html.erb
<nav class="navbar navbar-expand navbar-light bg-navbar topbar mb-4 static-top">
  <button id="sidebarToggleTop" class="btn btn-link rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>
  <ul class="navbar-nav ml-auto">
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-search fa-fw"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                aria-labelledby="searchDropdown">
        <form class="navbar-search">
          <div class="input-group">
            <input type="text" class="form-control bg-light border-1 small" placeholder="What do you want to look for?"
                      aria-label="Search" aria-describedby="basic-addon2" style="border-color: #3f51b5;">
            <div class="input-group-append">
              <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </li>
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-bell fa-fw"></i>
        <span class="badge badge-danger badge-counter">3+</span>
      </a>
      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="alertsDropdown">
        <h6 class="dropdown-header">
          Alerts Center
        </h6>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-primary">
              <i class="fas fa-file-alt text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 12, 2019</div>
            <span class="font-weight-bold">A new monthly report is ready to download!</span>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-success">
              <i class="fas fa-donate text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 7, 2019</div>
            $290.29 has been deposited into your account!
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-warning">
              <i class="fas fa-exclamation-triangle text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 2, 2019</div>
            Spending Alert: We've noticed unusually high spending for your account.
          </div>
        </a>
        <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
      </div>
    </li>
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-envelope fa-fw"></i>
        <span class="badge badge-warning badge-counter">2</span>
      </a>
      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="messagesDropdown">
        <h6 class="dropdown-header">
          Message Center
        </h6>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="/img/man.png" style="max-width: 60px" alt="">
            <div class="status-indicator bg-success"></div>
          </div>
          <div class="font-weight-bold">
            <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been
              having.</div>
            <div class="small text-gray-500">Udin Cilok · 58m</div>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="/img/girl.png" style="max-width: 60px" alt="">
            <div class="status-indicator bg-default"></div>
          </div>
          <div>
            <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people
              say this to all dogs, even if they aren't good...</div>
            <div class="small text-gray-500">Jaenab · 2w</div>
          </div>
        </a>
        <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
      </div>
    </li>
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-tasks fa-fw"></i>
        <span class="badge badge-success badge-counter">3</span>
      </a>
      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="messagesDropdown">
        <h6 class="dropdown-header">
          Task
        </h6>
        <a class="dropdown-item align-items-center" href="#">
          <div class="mb-3">
            <div class="small text-gray-500">Design Button
              <div class="small float-right"><b>50%</b></div>
            </div>
            <div class="progress" style="height: 12px;">
              <div class="progress-bar bg-success" role="progressbar" style="width: 50%" aria-valuenow="50"
                        aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>
        </a>
        <a class="dropdown-item align-items-center" href="#">
          <div class="mb-3">
            <div class="small text-gray-500">Make Beautiful Transitions
              <div class="small float-right"><b>30%</b></div>
            </div>
            <div class="progress" style="height: 12px;">
              <div class="progress-bar bg-warning" role="progressbar" style="width: 30%" aria-valuenow="30"
                        aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>
        </a>
        <a class="dropdown-item align-items-center" href="#">
          <div class="mb-3">
            <div class="small text-gray-500">Create Pie Chart
              <div class="small float-right"><b>75%</b></div>
            </div>
            <div class="progress" style="height: 12px;">
              <div class="progress-bar bg-danger" role="progressbar" style="width: 75%" aria-valuenow="75"
                        aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>
        </a>
        <a class="dropdown-item text-center small text-gray-500" href="#">View All Taks</a>
      </div>
    </li>
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="languagesDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
        <div class="d-inline"><img src=<%= "/img/language-#{I18n.locale}.png" %> alt="" /></div>
        <span class="ml-2 text-white small"><%= Settings.languages[I18n.locale] %></span>
      </a>
      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="languagesDropdown">
        <h6 class="dropdown-header">
          <%= t ".choose_language" %>
        </h6>
        <%= render "shared/list_languages" %>
      </div>
    </li>
    <div class="topbar-divider d-none d-sm-block"></div>
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
        <img class="img-profile rounded-circle" src="/img/boy.png" style="max-width: 60px">
        <span class="ml-2 d-none d-lg-inline text-white small"><%= current_user.email %></span>
      </a>
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        <a class="dropdown-item" href="#">
          <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
          Profile
        </a>
        <a class="dropdown-item" href="#">
          <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
          Settings
        </a>
        <a class="dropdown-item" href="#">
          <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
          Activity Log
        </a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="javascript:void(0);" data-toggle="modal" data-target="#logoutModal">
          <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
          Logout
        </a>
      </div>
    </li>
  </ul>
</nav>

app/views/admin/layouts/base.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="/img/logo/logo.png" rel="icon">
    <%= stylesheet_link_tag "admin", media: "all", "data-turbolinks-track": "reload" %>

  </head>
  <body id="page-top">
    <div id="wrapper">
      <%= render "admin/layouts/sidebar" %>
      <div id="content-wrapper" class="d-flex flex-column">
        <div id="content">
          <%= render "admin/layouts/topbar" %>
          <div class="container-fluid" id="container-wrapper">
            <%= render "admin/layouts/flash" %>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
    <%= javascript_pack_tag "admin", "data-turbolinks-track": "reload" %>
  </body>
</html>