config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    mount API::Root, at: "/"
    mount GrapeSwaggerRails::Engine, at: "/api-docs"
    namespace :admin do
      root "static_pages#index"
      get "login", to: "sessions#new"
      post "login", to: "sessions#create"
      get "logout", to: "sessions#destroy"
      resources :orders, except: %i(create destroy)
    end
    root "static_pages#index"
    get "/home", to: "static_pages#index"

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    get "/logout", to: "sessions#destroy"

    resources :products, only: %i(index show)
    resources :carts, except: %i(new show edit)
    resources :orders, only: %i(new create)
  end
end

app/views/layouts/_breadcrumbs.html.erb
<section class="breadcrumb-section set-bg" data-setbg="img/breadcrumb.jpg">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <div class="breadcrumb__text">
          <nav>
            <ol class="breadcrumb">
              <%= render_breadcrumbs tag: :li, separator: "/" %>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_cart_items.html.erb
<% if cart_contents.present? %>
  <% cart_contents.each do |item| %>
    <tr>
      <td class="shoping__cart__item">
        <img src="/img/cart/cart-1.jpg" alt="">
        <h5><%= item[1][:name] %></h5>
      </td>
      <td class="shoping__cart__price">
        <%= translate_price item[1][:price] %>
      </td>
      <td class="shoping__cart__price">
        <%= item[1][:inventory] %>
      </td>
      <td class="shoping__cart__quantity">
        <div class="quantity">
          <div class="pro-qty">
            <span class="dec qtybtn">-</span>
            <input type="text" readonly="readonly" value=<%= item[0][1] %>>
            <span class="inc qtybtn">+</span>
          </div>
        </div>
      </td>
      <td class="shoping__cart__total">
        <%= translate_price item[0][1] * item[1][:price] %>
      </td>
    </tr>
  <% end %>
<% end %>

app/views/layouts/_flash.html.erb
<div class="sticky-top">
  <% use_custom_flash! %>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <div class="container">
        <%= message.html_safe %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<!-- Footer Section Begin -->
<footer class="footer spad">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-md-6 col-sm-6">
        <div class="footer__about">
          <div class="footer__about__logo">
            <%= link_to root_path do %>
              <img src="/img/logo.png" alt="" />
            <% end %>
          </div>
          <ul>
            <li><%= t ".address", address: "236 Bạch Đằng, Phước Ninh, Hải Châu, Đà Nẵng" %></li>
            <li><%= t ".phone", phone_number: "0765 432 198" %></li>
            <li><%= t ".email", email: "admin@tlshop.example.com" %></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="footer__widget">
          <h6><%= t ".useful_links" %></h6>
          <ul>
            <li><a href=""><%= t ".about_us" %></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>
<!-- Footer Section End -->

app/views/layouts/_header.html.erb
<!-- Humberger Begin -->
<div class="humberger__menu__overlay"></div>
<div class="humberger__menu__wrapper">
  <div class="humberger__menu__logo">
    <%= link_to root_path do %>
      <img src="/img/logo.png" alt="" />
    <% end %>
  </div>
  <div class="humberger__menu__widget">
    <div class="header__top__right__language">
      <div class="flag__wrapper"><img src=<%= "/img/language-#{I18n.locale}.png" %> alt="" /></div>
      <div><%= Settings.languages[I18n.locale] %></div>
      <span class="arrow_carrot-down"></span>
      <%= render "shared/list_languages" %>
    </div>
  </div>
  <div class="header__top__right__auth">
    <% if current_user.present? %>
      <%= link_to "#" do %>
        <i class="fa fa-user"></i><%= current_user.first_name %>, <%= link_to t(".logout"), destroy_user_session_path %>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path do %>
        <i class="fa fa-user"></i><%= t ".login" %>
      <% end %>
    <% end %>
  </div>
  <nav class="humberger__menu__nav mobile-menu">
    <ul>
      <li class="active"><%= link_to t(".home"), root_path %></li>
      <li><%= link_to t(".shop"), products_path %></li>
      <li>
        <a><%= t ".order" %></a>
        <ul class="header__menu__dropdown">
          <li><%= link_to t(".cart"), carts_path %></li>
          <li><%= link_to t(".checkout"), "#" %></li>
        </ul>
      </li>
    </ul>
  </nav>
  <div id="mobile-menu-wrap"></div>
  <div class="humberger__menu__contact">
    <ul>
      <li><i class="fa fa-envelope"></i> <%= t ".site_email" %></li>
    </ul>
  </div>
</div>
<!-- Humberger End -->

<!-- Header Section Begin -->
<header class="header">
  <div class="header__top">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-6">
          <div class="header__top__left">
            <ul>
              <li><i class="fa fa-envelope"></i> <%= t ".site_email", email: "admin@tlshop.example.com" %></li>
            </ul>
          </div>
        </div>
        <div class="col-lg-6 col-md-6">
          <div class="header__top__right">
            <div class="header__top__right__language">
              <div class="flag__wrapper"><img src=<%= "/img/language-#{I18n.locale}.png" %> alt="" /></div>
              <div><%= Settings.languages[I18n.locale] %></div>
              <span class="arrow_carrot-down"></span>
              <%= render "shared/list_languages" %>
            </div>
            <div class="header__top__right__auth">
              <% if current_user.present? %>
                <%= link_to "#" do %>
                  <i class="fa fa-user"></i><%= current_user.first_name %>, <%= link_to t(".logout"), destroy_user_session_path %>
                <% end %>
              <% else %>
                <%= link_to new_user_session_path do %>
                  <i class="fa fa-user"></i><%= t ".login" %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-3">
        <div class="header__logo">
          <%= link_to root_path do %>
            <img src="/img/logo.png" alt="" />
          <% end %>
        </div>
      </div>
      <div class="col-lg-6">
        <nav class="header__menu">
          <ul>
            <li><%= link_to t(".home"), root_path %></li>
            <li><%= link_to t(".shop"), products_path %></li>
            <li>
              <a href="#"><%= t ".order" %></a>
              <ul class="header__menu__dropdown">
                <li><%= link_to t(".cart"), carts_path %></li>
                <li><%= link_to t(".checkout"), "#" %></li>
              </ul>
            </li>
          </ul>
        </nav>
      </div>
      <div class="col-lg-3">
        <div class="header__cart">
          <ul>
            <li>
              <%= link_to carts_path do %>
                <i class="fa fa-shopping-bag"></i>
                <span id="shopping__bag__count"><%= cart_count %></span>
              <% end %>
            </li>
          </ul>
          <div class="header__cart__price">
            <%= t "layouts.header.total" %>
            <span id="shopping__bag__total"><%= translate_price subtotal %></span>
          </div>
        </div>
      </div>
    </div>
    <div class="humberger__open">
      <i class="fa fa-bars"></i>
    </div>
  </div>
</header>
<!-- Header Section End -->

app/views/layouts/_hero.html.erb
<!-- Hero Section Begin -->
<section class="hero">
  <div class="container">
    <div class="row">
      <div class="col-lg-3">
        <div class="hero__categories">
          <div class="hero__categories__all">
            <i class="fa fa-bars"></i>
            <span><%= t "labels.category.cat" %></span>
          </div>
          <ul class="category-hierachy">
            <% parent_categories.each do |category| %>
              <li class="toggle-down-wrapper">
                <div>
                  <h4 class="d-inline-block"><%= link_to category.title, products_path(filters: {category_in:[category.id.to_s]}) %></h4>
                  <% if category.children.any? %>
                    <span class="fas fa-angle-down toggle-down-main clickable"></span>
                  <% end %>
                </div>
                <% if category.children.any? %>
                  <ul class="toggle-down-content border-success">
                    <% category.children.each do |subcategory| %>
                      <li>
                        <h5><%= link_to subcategory.title, products_path(filters: {category_in:[subcategory.id.to_s]}) %></h5>
                      </li>
                    <% end %>
                  </ul>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="col-lg-9">
        <div class="hero__search">
          <div class="hero__search__form">
            <%= form_for :filters, url: products_url, method: :get  do |f| %>
              <div class="hero__search__categories">
                <%= t "labels.category.all" %>
              </div>
              <%= f.text_field :name_cont, placeholder: t(".what_do_you_need?") %>
              <%= f.button t(".search_btn_txt"), name: nil, class: "site-btn"%>
            <% end %>
          </div>
          <div class="hero__search__phone">
            <div class="hero__search__phone__icon">
              <i class="fa fa-phone"></i>
            </div>
            <div class="hero__search__phone__text">
              <h5><%= t ".phone", phone_number: "0765 432 198" %></h5>
              <span><%= t ".support" %></span>
            </div>
          </div>
        </div>
        <div class="hero__item set-bg" data-setbg="/img/hero/banner.jpg">
          <!-- <div class="hero__text">
            <span>FRUIT FRESH</span>
            <h2>Vegetable <br />
              100% Organic</h2>
            <p>Free Pickup and Delivery Available</p>
            <a href="#" class="primary-btn">SHOP NOW</a>
          </div> -->
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Hero Section End -->

app/views/layouts/_product_card.html.erb
<%
  default_classes = "col-lg-3 col-md-4 col-sm-6 "
  classes = classes || []
%>
<div class="<%= default_classes + snake_join(classes)%>">
  <div class="featured__item">
    <div class="featured__item__pic set-bg" data-setbg="img/featured/feature-1.jpg">
      <ul class="featured__item__pic__hover">
        <li>
          <%= link_to carts_path(id: product.id), method: "post", remote: true do %>
            <i class="fa fa-shopping-cart"></i>
          <% end %>
        </li>
      </ul>
    </div>
    <div class="featured__item__text">
      <h6><%= link_to product.name, product_path(product) %></h6>
      <h5><%= translate_price product.price %></h5>
    </div>
  </div>
</div>

app/views/layouts/_product_carousel.html.erb
<%= link_to(product_path(product), class: "latest-product__item") do %>
  <div class="latest-product__item__pic">
    <img src="/img/latest-product/lp-1.jpg" alt="" />
  </div>
  <div class="latest-product__item__text">
    <h5><%= product.name %></h5>
    <p><span><%= translate_price product.price %></span></p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>

  </head>

  <body>
    <!-- Page Preloder -->
    <div id="preloder">
      <div class="loader"></div>
    </div>
    <%= render "layouts/flash" %>
    <%= render "layouts/header" %>
    <% if @use_layout_auth %>
      <div class="container my-3">
        <%= yield %>
      </div>
    <% else %>
      <%= render "layouts/hero" %>
      <div class="pending__popup"></div>
      <%= yield %>
    <% end %>
    <%= render "layouts/footer" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </body>
</html>